"""
ui/app.py
=========
Streamlit UI — RACE Reading Comprehension & Quiz Generation System.
Traditional ML only (no neural networks).
"""

from __future__ import annotations

import json
import os
import random
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

# ── Path bootstrap so `src.*` resolves ────────────────────────────────────────
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.inference import (
    predict_answer,
    generate_question,
    generate_distractors,
    generate_hints,
)

PROCESSED_DIR = ROOT / "data" / "processed"
REPORTS_DIR = ROOT / "reports"
METRICS_PATH = REPORTS_DIR / "metrics_test.json"

# ══════════════════════════════════════════════════════════════════════════════
#  Page config — must be first Streamlit call
# ══════════════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="RACE RC Quiz System",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
.stButton > button { border-radius: 8px; font-weight: 600; }
.correct-badge  { color: #16a34a; font-weight: 700; font-size: 1.1rem; }
.wrong-badge    { color: #dc2626; font-weight: 700; font-size: 1.1rem; }
.hint-box {
    background: #fffbeb; border-left: 4px solid #f59e0b;
    padding: 0.75rem 1rem; border-radius: 6px; margin-bottom: 0.5rem;
}
.ai-badge {
    background: #e0e7ff; color: #3730a3; font-size: 0.75rem;
    padding: 2px 8px; border-radius: 12px; font-weight: 600;
}
</style>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
#  Cached loaders
# ══════════════════════════════════════════════════════════════════════════════

@st.cache_data(show_spinner="Loading RACE test samples …")
def load_race_samples(n: int = 200) -> list[dict]:
    """Load test samples from local processed CSV."""
    csv = PROCESSED_DIR / "test.csv"
    if not csv.exists():
        return []
    df = pd.read_csv(csv).head(n)
    out = []
    for _, r in df.iterrows():
        out.append({
            "article": r.get("article", ""),
            "question": r.get("question", ""),
            "answer": str(r.get("answer", "A")).upper(),
            "A": r.get("A", ""), "B": r.get("B", ""),
            "C": r.get("C", ""), "D": r.get("D", ""),
        })
    return out


@st.cache_data(show_spinner=False)
def load_test_metrics() -> dict | None:
    if METRICS_PATH.exists():
        try:
            return json.loads(METRICS_PATH.read_text())
        except Exception:
            return None
    return None


# ══════════════════════════════════════════════════════════════════════════════
#  Session state
# ══════════════════════════════════════════════════════════════════════════════

def _init_state():
    defaults = {
        "screen": "input",
        "passage": "",
        "pipeline_result": None,
        "user_choice": None,
        "answer_checked": False,
        "hints_revealed": 0,
        "session_log": [],
        "race_samples": [],
        "current_sample": None,
        "verifier_log": [],
        "latency_log": [],
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v


_init_state()


# ══════════════════════════════════════════════════════════════════════════════
#  Sidebar
# ══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.title("📚 RACE RC Quiz System")
    st.caption("Traditional ML pipeline (no neural networks)")
    st.divider()
    nav = st.radio(
        "Navigation",
        ["🏠 Article Input", "❓ Quiz View", "💡 Hint Panel", "📊 Analytics"],
        index=["input", "quiz", "hints", "analytics"].index(st.session_state.screen)
              if st.session_state.screen in ["input", "quiz", "hints", "analytics"] else 0,
    )
    screen_map = {"🏠 Article Input": "input", "❓ Quiz View": "quiz",
                  "💡 Hint Panel": "hints", "📊 Analytics": "analytics"}
    st.session_state.screen = screen_map[nav]
    st.divider()
    st.markdown('<span class="ai-badge">⚠️ AI-Generated Content</span>',
                unsafe_allow_html=True)
    st.caption("Questions and distractors are auto-generated by traditional ML; verify before use.")


# ══════════════════════════════════════════════════════════════════════════════
#  Pipeline runner
# ══════════════════════════════════════════════════════════════════════════════

def _run_pipeline(passage: str, ground_truth_answer: str | None = None,
                   gt_options: dict | None = None,
                   reference_question: str | None = None) -> dict:
    """
    Generate question, distractors, and hints. Picks ground-truth answer when
    provided (RACE sample); otherwise the system picks the longest option-like
    candidate phrase from the passage.
    """
    # Determine answer text used as input to the generator
    if ground_truth_answer:
        answer_text = ground_truth_answer
    else:
        # Heuristic for custom-pasted text: use first 4 words as a stub answer
        answer_text = " ".join(passage.split()[:4]) or "the topic"

    # Generate question
    t0 = time.perf_counter()
    question = generate_question(passage, answer_text)
    latency_q_ms = (time.perf_counter() - t0) * 1000
    st.session_state.latency_log.append(latency_q_ms)

    # Generate distractors
    t0 = time.perf_counter()
    distractors = generate_distractors(passage, question, answer_text)
    latency_d_ms = (time.perf_counter() - t0) * 1000
    st.session_state.latency_log.append(latency_d_ms)

    # Generate hints
    t0 = time.perf_counter()
    hints = generate_hints(passage, question, answer_text)
    latency_h_ms = (time.perf_counter() - t0) * 1000
    st.session_state.latency_log.append(latency_h_ms)

    # Build options A–D with shuffled positions
    options_list = list(distractors[:3]) + [answer_text]
    rng = random.Random(42)
    rng.shuffle(options_list)
    correct_label = ["A", "B", "C", "D"][options_list.index(answer_text)]
    option_map = dict(zip(["A", "B", "C", "D"], options_list))

    # Per-inference NLP score (if reference question available)
    nlp_metrics = {}
    if reference_question:
        from src.evaluate_nlp import score_single
        nlp_metrics = score_single(question, reference_question)

    return {
        "passage": passage,
        "question": question,
        "answer": answer_text,
        "correct_label": correct_label,
        "option_map": option_map,
        "distractors": distractors,
        "hints": hints,
        "latency_q_ms": round(latency_q_ms, 2),
        "latency_d_ms": round(latency_d_ms, 2),
        "latency_h_ms": round(latency_h_ms, 2),
        "nlp_metrics": nlp_metrics,
        "has_race_reference": reference_question is not None,
    }


# ══════════════════════════════════════════════════════════════════════════════
#  Screen 1 — Article Input
# ══════════════════════════════════════════════════════════════════════════════

def screen_input():
    st.header("🏠 Screen 1 — Article Input")
    st.caption("Paste a passage, upload a .txt file, or load a random RACE sample.")

    col_left, col_right = st.columns([3, 1])
    with col_right:
        st.markdown("#### Quick Load")
        if st.button("🎲 Random RACE Sample", use_container_width=True):
            if not st.session_state.race_samples:
                st.session_state.race_samples = load_race_samples()
            if st.session_state.race_samples:
                sample = random.choice(st.session_state.race_samples)
                st.session_state.passage = sample["article"]
                st.session_state.current_sample = sample
            else:
                st.warning("No RACE samples available. Run preprocessing.py first.")

        uploaded = st.file_uploader("Upload .txt", type=["txt"])
        if uploaded:
            st.session_state.passage = uploaded.read().decode("utf-8")
            st.session_state.current_sample = None

    with col_left:
        passage = st.text_area(
            "Reading Passage",
            value=st.session_state.passage,
            height=320,
            placeholder="Paste a reading passage of at least 30 words …",
            key="passage_area",
        )
        st.session_state.passage = passage

    word_count = len(passage.split()) if passage.strip() else 0
    st.caption(f"Word count: {word_count}")
    if word_count < 30:
        st.info("Please provide a passage of at least 30 words.")

    st.divider()
    if st.button("🚀 Generate Quiz", type="primary",
                 disabled=word_count < 30, use_container_width=False):
        sample = st.session_state.get("current_sample")
        gt_answer = sample[sample["answer"]] if sample else None
        gt_options = (
            {"A": sample["A"], "B": sample["B"], "C": sample["C"], "D": sample["D"]}
            if sample else None
        )
        ref_q = sample["question"] if sample else None

        with st.spinner("Generating quiz with traditional ML pipeline …"):
            try:
                result = _run_pipeline(passage, gt_answer, gt_options, ref_q)
            except FileNotFoundError as e:
                st.error(f"Models missing: {e}")
                st.info("Run `python src/preprocessing.py` then "
                        "`python src/model_a_train.py`, `python src/template_generator.py`, "
                        "and `python src/model_b_train.py` to train all components.")
                return
            except ValueError as e:
                st.error(str(e))
                return

        st.session_state.pipeline_result = result
        st.session_state.user_choice = None
        st.session_state.answer_checked = False
        st.session_state.hints_revealed = 0
        st.session_state.session_log.append({
            "passage": passage[:80],
            "question": result["question"],
            "answer": result["answer"],
            "latency_q_ms": result["latency_q_ms"],
            "latency_d_ms": result["latency_d_ms"],
            "latency_h_ms": result["latency_h_ms"],
        })
        st.session_state.screen = "quiz"
        st.rerun()


# ══════════════════════════════════════════════════════════════════════════════
#  Screen 2 — Quiz View
# ══════════════════════════════════════════════════════════════════════════════

def screen_quiz():
    st.header("❓ Screen 2 — Quiz View")
    result = st.session_state.pipeline_result
    if not result:
        st.warning("No quiz generated yet. Go to Article Input first.")
        return

    st.markdown(f"**Passage excerpt:** _{result['passage'][:200]} …_")
    st.divider()
    st.markdown('<span class="ai-badge">⚠️ AI-Generated Question</span>',
                unsafe_allow_html=True)
    st.markdown(f"### {result['question']}")
    st.caption(f"Generation latency: {result['latency_q_ms']:.0f} ms")

    st.markdown("---")
    st.markdown("**Choose your answer:**")
    for label in ["A", "B", "C", "D"]:
        text = result["option_map"][label]
        if st.button(f"**{label}.** {text}", key=f"opt_{label}",
                     use_container_width=True):
            st.session_state.user_choice = label
            st.session_state.answer_checked = False

    st.divider()
    if st.session_state.user_choice:
        col_check, col_hint = st.columns([1, 1])
        with col_check:
            if st.button("✅ Check Answer", type="primary"):
                st.session_state.answer_checked = True
        with col_hint:
            if st.button("💡 Need a Hint?"):
                st.session_state.screen = "hints"
                st.rerun()

    if st.session_state.answer_checked and st.session_state.user_choice:
        chosen = st.session_state.user_choice
        correct = result["correct_label"]

        # Verifier prediction
        try:
            verifier_label, conf = predict_answer(
                result["passage"], result["question"], result["option_map"]
            )
        except Exception as e:
            verifier_label, conf = correct, 0.0
            st.caption(f"Verifier unavailable ({e}).")

        # Update verifier log: 1 if verifier picked the same label as ground truth
        st.session_state.verifier_log.append({
            "y_true": 1 if chosen == correct else 0,
            "y_pred": 1 if verifier_label == correct else 0,
            "confidence": float(conf),
        })

        if chosen == correct:
            st.markdown(
                f'<p class="correct-badge">✅ Correct! '
                f'The answer is {correct}: {result["option_map"][correct]}</p>',
                unsafe_allow_html=True)
            st.balloons()
        else:
            st.markdown(
                f'<p class="wrong-badge">❌ Incorrect. You chose {chosen}. '
                f'The correct answer is {correct}: {result["option_map"][correct]}</p>',
                unsafe_allow_html=True)

        st.markdown(
            f"**Model A Verifier (LR+SVM+NB ensemble):** predicted "
            f"`{verifier_label}` with confidence **{conf:.2%}**."
        )


# ══════════════════════════════════════════════════════════════════════════════
#  Screen 3 — Hints (graduated)
# ══════════════════════════════════════════════════════════════════════════════

def screen_hints():
    st.header("💡 Screen 3 — Hint Panel")
    result = st.session_state.pipeline_result
    if not result:
        st.warning("No quiz generated yet. Go to Article Input first.")
        return

    st.markdown(f"**Question:** _{result['question']}_")
    st.caption(f"Hint latency: {result['latency_h_ms']:.0f} ms")
    st.divider()

    hints = result.get("hints", [])
    if not hints:
        st.info("No hints generated.")
        return

    labels = ["Hint 1 — General Clue", "Hint 2 — More Specific",
              "Hint 3 — Near-Explicit"]
    revealed = st.session_state.hints_revealed

    for i, (lbl, hint) in enumerate(zip(labels, hints)):
        if i < revealed:
            st.markdown(f'<div class="hint-box"><b>{lbl}:</b> {hint}</div>',
                         unsafe_allow_html=True)
        else:
            st.markdown(
                f'<div class="hint-box" style="filter:blur(4px);user-select:none">'
                f'<b>{lbl}:</b> {hint}</div>',
                unsafe_allow_html=True)

    col_a, col_b = st.columns([1, 1])
    with col_a:
        if revealed < len(hints):
            if st.button("🔓 Show Next Hint", type="primary"):
                st.session_state.hints_revealed += 1
                st.rerun()
        else:
            st.success("All hints revealed.")

    with col_b:
        if st.button("🏳️ Reveal Answer",
                     disabled=(revealed < len(hints))):
            st.info(f"**Correct Answer:** {result['answer']}")


# ══════════════════════════════════════════════════════════════════════════════
#  Screen 4 — Analytics
# ══════════════════════════════════════════════════════════════════════════════

def screen_analytics():
    import plotly.graph_objects as go

    st.header("📊 Screen 4 — Analytics Dashboard")

    # ── Verifier classification metrics ──────────────────────────────────────
    st.subheader("Model A — Verifier Performance (session)")
    verifier_log = st.session_state.verifier_log
    if not verifier_log:
        st.info("Use **Check Answer** on Screen 2 to accumulate verifier predictions.")
    else:
        from sklearn.metrics import (accuracy_score, precision_score,
                                       recall_score, f1_score, confusion_matrix)
        y_true = np.array([e["y_true"] for e in verifier_log])
        y_pred = np.array([e["y_pred"] for e in verifier_log])
        acc = accuracy_score(y_true, y_pred)
        precision = precision_score(y_true, y_pred, average="macro", zero_division=0)
        recall = recall_score(y_true, y_pred, average="macro", zero_division=0)
        f1 = f1_score(y_true, y_pred, average="macro", zero_division=0)

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Accuracy", f"{acc:.3f}")
        c2.metric("Precision (macro)", f"{precision:.3f}")
        c3.metric("Recall (macro)", f"{recall:.3f}")
        c4.metric("F1 (macro)", f"{f1:.3f}")

        cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
        if cm.size == 4:
            tn, fp, fn, tp = cm.ravel()
            st.markdown("**Confusion Matrix**")
            cc1, cc2, cc3, cc4 = st.columns(4)
            cc1.metric("TP", int(tp)); cc2.metric("TN", int(tn))
            cc3.metric("FP", int(fp)); cc4.metric("FN", int(fn))

    st.divider()

    # ── Corpus-level NLP metrics from metrics_test.json ──────────────────────
    st.subheader("Corpus-level NLP Metrics (BLEU · ROUGE-L · METEOR)")
    metrics = load_test_metrics()
    if metrics is None:
        st.info("Run `python src/evaluate_nlp.py` to generate metrics_test.json.")
    else:
        for section_key, section_title in (
            ("model_a", "Model A — Question Generation"),
            ("model_b_distractors", "Model B — Distractors"),
            ("model_b_hints", "Model B — Hints"),
        ):
            block = metrics.get(section_key, {})
            if not block:
                continue
            st.markdown(f"**{section_title}** (n={block.get('num_samples', '—')})")
            cols = st.columns(4)
            cols[0].metric("BLEU-1", f"{block.get('bleu_1', 0):.4f}")
            cols[1].metric("BLEU-4", f"{block.get('bleu_4', 0):.4f}")
            cols[2].metric("ROUGE-L F1", f"{block.get('rouge_l_f1', 0):.4f}")
            cols[3].metric("METEOR", f"{block.get('meteor', 0):.4f}")

    st.divider()

    # ── Latency tracking ─────────────────────────────────────────────────────
    st.subheader("Inference Latency")
    if st.session_state.latency_log:
        lat = st.session_state.latency_log
        fig = go.Figure(go.Scatter(y=lat, mode="lines+markers"))
        fig.update_layout(yaxis_title="Latency (ms)", xaxis_title="Inference call #",
                          height=300, title="Per-inference latency (this session)")
        st.plotly_chart(fig, use_container_width=True)
        st.caption(f"Mean latency: {np.mean(lat):.1f} ms · "
                   f"Max: {np.max(lat):.1f} ms")

    # ── Session log + CSV download ───────────────────────────────────────────
    if st.session_state.session_log:
        st.subheader("Session Log")
        df = pd.DataFrame(st.session_state.session_log)
        st.dataframe(df, use_container_width=True)
        csv = df.to_csv(index=False).encode("utf-8")
        st.download_button("⬇️ Export Session Log (CSV)", csv,
                           file_name="session_log.csv", mime="text/csv")


# ══════════════════════════════════════════════════════════════════════════════
#  Router
# ══════════════════════════════════════════════════════════════════════════════

screen = st.session_state.screen
if screen == "input":
    screen_input()
elif screen == "quiz":
    screen_quiz()
elif screen == "hints":
    screen_hints()
elif screen == "analytics":
    screen_analytics()
else:
    screen_input()
